name: Build and Release

on: [push]
permissions: write-all

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Node actions
        uses: actions/setup-node@v3
        with:
          node-version: ^18.17
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${secrets.GITHUB_TOKEN}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
